/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ypAoDi7LGAO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { JSX, SVGProps } from "react"

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function SalahEducation() {
  return (
    <section className="py-12 md:py-24 lg:py-32">
      <div className="container grid max-w-5xl items-center justify-center gap-8 px-4 md:px-6 lg:grid-cols-2 lg:gap-12 xl:max-w-6xl">
        <div className="space-y-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Education</h2>
            <p className="text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Salah Eddine Arbani's academic journey and qualifications.
            </p>
          </div>
          <div className="grid gap-6">
            <div className="grid gap-2">
              <h3 className="text-xl font-semibold">
                <GraduationCapIcon className="mr-2 inline-block h-6 w-6" />
                Master of Science in Computer Science
              </h3>
              <p className="text-muted-foreground">
                <BuildingIcon className="mr-2 inline-block h-5 w-5" />
                University of California, Berkeley
              </p>
              <p className="text-muted-foreground">
                <CalendarIcon className="mr-2 inline-block h-5 w-5" />
                2018 - 2020
              </p>
            </div>
            <div className="grid gap-2">
              <h3 className="text-xl font-semibold">
                <GraduationCapIcon className="mr-2 inline-block h-6 w-6" />
                Bachelor of Science in Computer Engineering
              </h3>
              <p className="text-muted-foreground">
                <BuildingIcon className="mr-2 inline-block h-5 w-5" />
                Massachusetts Institute of Technology (MIT)
              </p>
              <p className="text-muted-foreground">
                <CalendarIcon className="mr-2 inline-block h-5 w-5" />
                2014 - 2018
              </p>
            </div>
            <div className="grid gap-2">
              <h3 className="text-xl font-semibold">
                <BriefcaseIcon className="mr-2 inline-block h-6 w-6" />
                Specializations
              </h3>
              <ul className="space-y-1 text-muted-foreground">
                <li>
                  <LightbulbIcon className="mr-2 inline-block h-5 w-5" />
                  Artificial Intelligence
                </li>
                <li>
                  <LightbulbIcon className="mr-2 inline-block h-5 w-5" />
                  Machine Learning
                </li>
                <li>
                  <LightbulbIcon className="mr-2 inline-block h-5 w-5" />
                  Data Science
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="rounded-lg border bg-muted p-6 shadow-sm">
          <img
            src="/placeholder.svg"
            width={500}
            height={500}
            alt="Salah Eddine Arbani"
            className="mx-auto aspect-square overflow-hidden rounded-lg object-cover"
          />
        </div>
      </div>
    </section>
  )
}

function BriefcaseIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function BuildingIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="20" x="4" y="2" rx="2" ry="2" />
      <path d="M9 22v-4h6v4" />
      <path d="M8 6h.01" />
      <path d="M16 6h.01" />
      <path d="M12 6h.01" />
      <path d="M12 10h.01" />
      <path d="M12 14h.01" />
      <path d="M16 10h.01" />
      <path d="M16 14h.01" />
      <path d="M8 10h.01" />
      <path d="M8 14h.01" />
    </svg>
  )
}


function CalendarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function GraduationCapIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z" />
      <path d="M22 10v6" />
      <path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5" />
    </svg>
  )
}


function LightbulbIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>
  )
}
