/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bfVkOtFRKyZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function SalahSkils() {
  return (
    <section className="py-12 md:py-24 lg:py-32 bg-background">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-8 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Skills</h2>
            <p className="max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Salah Eddine Arbani's technical and soft skills.
            </p>
          </div>
          <div className="grid w-full max-w-4xl grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">
            <div className="flex flex-col items-center justify-center gap-4">
              <div className="bg-primary rounded-full p-4 text-primary-foreground">
                <CodepenIcon className="h-8 w-8" />
              </div>
              <div className="space-y-2">
                <h3 className="text-lg font-bold">React</h3>
                <div className="relative h-2 w-full rounded-full bg-muted">
                  <div className="absolute left-0 top-0 h-full w-[90%] rounded-full bg-primary" />
                </div>
                <div className="text-sm text-muted-foreground">90% Proficiency</div>
              </div>
            </div>
            <div className="flex flex-col items-center justify-center gap-4">
              <div className="bg-primary rounded-full p-4 text-primary-foreground">
                <FastForwardIcon className="h-8 w-8" />
              </div>
              <div className="space-y-2">
                <h3 className="text-lg font-bold">Next.js</h3>
                <div className="relative h-2 w-full rounded-full bg-muted">
                  <div className="absolute left-0 top-0 h-full w-[85%] rounded-full bg-primary" />
                </div>
                <div className="text-sm text-muted-foreground">85% Proficiency</div>
              </div>
            </div>
            <div className="flex flex-col items-center justify-center gap-4">
              <div className="bg-primary rounded-full p-4 text-primary-foreground">
                <TypeIcon className="h-8 w-8" />
              </div>
              <div className="space-y-2">
                <h3 className="text-lg font-bold">TypeScript</h3>
                <div className="relative h-2 w-full rounded-full bg-muted">
                  <div className="absolute left-0 top-0 h-full w-[92%] rounded-full bg-primary" />
                </div>
                <div className="text-sm text-muted-foreground">92% Proficiency</div>
              </div>
            </div>
            <div className="flex flex-col items-center justify-center gap-4">
              <div className="bg-primary rounded-full p-4 text-primary-foreground">
                <NetworkIcon className="h-8 w-8" />
              </div>
              <div className="space-y-2">
                <h3 className="text-lg font-bold">Node.js</h3>
                <div className="relative h-2 w-full rounded-full bg-muted">
                  <div className="absolute left-0 top-0 h-full w-[88%] rounded-full bg-primary" />
                </div>
                <div className="text-sm text-muted-foreground">88% Proficiency</div>
              </div>
            </div>
            <div className="col-span-1 sm:col-span-2 lg:col-span-4 flex flex-col items-center justify-center gap-4">
              <div className="space-y-2">
                <h3 className="text-lg font-bold">Soft Skills</h3>
                <div className="grid grid-cols-3 gap-4">
                  <div className="flex flex-col items-center justify-center gap-2">
                    <div className="bg-primary rounded-full p-4 text-primary-foreground">
                      <ContactIcon className="h-8 w-8" />
                    </div>
                    <div className="text-sm text-muted-foreground">Communication</div>
                  </div>
                  <div className="flex flex-col items-center justify-center gap-2">
                    <div className="bg-primary rounded-full p-4 text-primary-foreground">
                      <WorkflowIcon className="h-8 w-8" />
                    </div>
                    <div className="text-sm text-muted-foreground">Teamwork</div>
                  </div>
                  <div className="flex flex-col items-center justify-center gap-2">
                    <div className="bg-primary rounded-full p-4 text-primary-foreground">
                      <PuzzleIcon className="h-8 w-8" />
                    </div>
                    <div className="text-sm text-muted-foreground">Problem Solving</div>
                  </div>
                  <div className="flex flex-col items-center justify-center gap-2">
                    <div className="bg-primary rounded-full p-4 text-primary-foreground">
                      <AccessibilityIcon className="h-8 w-8" />
                    </div>
                    <div className="text-sm text-muted-foreground">Adaptability</div>
                  </div>
                  <div className="flex flex-col items-center justify-center gap-2">
                    <div className="bg-primary rounded-full p-4 text-primary-foreground">
                      <CreativeCommonsIcon className="h-8 w-8" />
                    </div>
                    <div className="text-sm text-muted-foreground">Creativity</div>
                  </div>
                  <div className="flex flex-col items-center justify-center gap-2">
                    <div className="bg-primary rounded-full p-4 text-primary-foreground">
                      <BadgeIcon className="h-8 w-8" />
                    </div>
                    <div className="text-sm text-muted-foreground">Leadership</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

function AccessibilityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="16" cy="4" r="1" />
      <path d="m18 19 1-7-6 1" />
      <path d="m5 8 3-3 5.5 3-2.36 3.5" />
      <path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
      <path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
    </svg>
  )
}


function BadgeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
    </svg>
  )
}


function CodepenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function ContactIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 18a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <circle cx="12" cy="10" r="2" />
      <line x1="8" x2="8" y1="2" y2="4" />
      <line x1="16" x2="16" y1="2" y2="4" />
    </svg>
  )
}


function CreativeCommonsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M10 9.3a2.8 2.8 0 0 0-3.5 1 3.1 3.1 0 0 0 0 3.4 2.7 2.7 0 0 0 3.5 1" />
      <path d="M17 9.3a2.8 2.8 0 0 0-3.5 1 3.1 3.1 0 0 0 0 3.4 2.7 2.7 0 0 0 3.5 1" />
    </svg>
  )
}


function FastForwardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="13 19 22 12 13 5 13 19" />
      <polygon points="2 19 11 12 2 5 2 19" />
    </svg>
  )
}


function NetworkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>
  )
}


function PuzzleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19.439 7.85c-.049.322.059.648.289.878l1.568 1.568c.47.47.706 1.087.706 1.704s-.235 1.233-.706 1.704l-1.611 1.611a.98.98 0 0 1-.837.276c-.47-.07-.802-.48-.968-.925a2.501 2.501 0 1 0-3.214 3.214c.446.166.855.497.925.968a.979.979 0 0 1-.276.837l-1.61 1.61a2.404 2.404 0 0 1-1.705.707 2.402 2.402 0 0 1-1.704-.706l-1.568-1.568a1.026 1.026 0 0 0-.877-.29c-.493.074-.84.504-1.02.968a2.5 2.5 0 1 1-3.237-3.237c.464-.18.894-.527.967-1.02a1.026 1.026 0 0 0-.289-.877l-1.568-1.568A2.402 2.402 0 0 1 1.998 12c0-.617.236-1.234.706-1.704L4.23 8.77c.24-.24.581-.353.917-.303.515.077.877.528 1.073 1.01a2.5 2.5 0 1 0 3.259-3.259c-.482-.196-.933-.558-1.01-1.073-.05-.336.062-.676.303-.917l1.525-1.525A2.402 2.402 0 0 1 12 1.998c.617 0 1.234.236 1.704.706l1.568 1.568c.23.23.556.338.877.29.493-.074.84-.504 1.02-.968a2.5 2.5 0 1 1 3.237 3.237c-.464.18-.894.527-.967 1.02Z" />
    </svg>
  )
}


function TypeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 7 4 4 20 4 20 7" />
      <line x1="9" x2="15" y1="20" y2="20" />
      <line x1="12" x2="12" y1="4" y2="20" />
    </svg>
  )
}


function WorkflowIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="8" x="3" y="3" rx="2" />
      <path d="M7 11v4a2 2 0 0 0 2 2h4" />
      <rect width="8" height="8" x="13" y="13" rx="2" />
    </svg>
  )
}
