/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mtvIqfOE5Ft
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { JSX, SVGProps } from "react"

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function SalahAwards() {
  return (
    <section className="max-w-6xl mx-auto py-12 md:py-16 lg:py-20">
      <div className="flex flex-col items-center space-y-6 md:space-y-8 lg:space-y-10">
        <div className="text-center space-y-2">
          <h2 className="text-2xl font-bold tracking-tight sm:text-3xl md:text-4xl">Achievements & Awards</h2>
          <p className="text-muted-foreground md:text-lg">Recognition for my work and contributions.</p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6 lg:gap-8 w-full">
          <div className="bg-background rounded-lg shadow-lg p-4 md:p-6 flex flex-col items-start gap-3">
            <div className="bg-primary rounded-full w-10 h-10 flex items-center justify-center">
              <TrophyIcon className="w-5 h-5 text-primary-foreground" />
            </div>
            <h3 className="text-lg font-semibold">Best UI/UX Design</h3>
            <p className="text-muted-foreground text-sm md:text-base">
              Awarded for exceptional user experience design at the 2022 Design Awards.
            </p>
          </div>
          <div className="bg-background rounded-lg shadow-lg p-4 md:p-6 flex flex-col items-start gap-3">
            <div className="bg-secondary rounded-full w-10 h-10 flex items-center justify-center">
              <MedalIcon className="w-5 h-5 text-secondary-foreground" />
            </div>
            <h3 className="text-lg font-semibold">Top Contributor</h3>
            <p className="text-muted-foreground text-sm md:text-base">
              Recognized as a top contributor to the open-source community in 2021.
            </p>
          </div>
          <div className="bg-background rounded-lg shadow-lg p-4 md:p-6 flex flex-col items-start gap-3">
            <div className="bg-muted rounded-full w-10 h-10 flex items-center justify-center">
              <StarIcon className="w-5 h-5 text-muted-foreground" />
            </div>
            <h3 className="text-lg font-semibold">Startup Accelerator</h3>
            <p className="text-muted-foreground text-sm md:text-base">
              Participated in the prestigious XYZ Startup Accelerator program in 2020.
            </p>
          </div>
          <div className="bg-background rounded-lg shadow-lg p-4 md:p-6 flex flex-col items-start gap-3">
            <div className="bg-accent rounded-full w-10 h-10 flex items-center justify-center">
              <BriefcaseIcon className="w-5 h-5 text-accent-foreground" />
            </div>
            <h3 className="text-lg font-semibold">Entrepreneur of the Year</h3>
            <p className="text-muted-foreground text-sm md:text-base">
              Recognized as the Entrepreneur of the Year by the local chamber of commerce.
            </p>
          </div>
          <div className="bg-background rounded-lg shadow-lg p-4 md:p-6 flex flex-col items-start gap-3">
            <div className="bg-primary rounded-full w-10 h-10 flex items-center justify-center">
              <AwardIcon className="w-5 h-5 text-primary-foreground" />
            </div>
            <h3 className="text-lg font-semibold">Best Mobile App</h3>
            <p className="text-muted-foreground text-sm md:text-base">
              Awarded for the best mobile app design at the 2021 Mobile App Awards.
            </p>
          </div>
          <div className="bg-background rounded-lg shadow-lg p-4 md:p-6 flex flex-col items-start gap-3">
            <div className="bg-secondary rounded-full w-10 h-10 flex items-center justify-center">
              <BadgeIcon className="w-5 h-5 text-secondary-foreground" />
            </div>
            <h3 className="text-lg font-semibold">Certified Expert</h3>
            <p className="text-muted-foreground text-sm md:text-base">
              Earned the prestigious XYZ Certified Expert certification in 2022.
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}

function AwardIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526" />
      <circle cx="12" cy="8" r="6" />
    </svg>
  )
}


function BadgeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
    </svg>
  )
}


function BriefcaseIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function MedalIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15" />
      <path d="M11 12 5.12 2.2" />
      <path d="m13 12 5.88-9.8" />
      <path d="M8 7h8" />
      <circle cx="12" cy="17" r="5" />
      <path d="M12 18v-2h-.5" />
    </svg>
  )
}


function StarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function TrophyIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>
  )
}
