/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7jtLE7vGYXP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function SalahArticles() {
  return (
    <section className="py-12 md:py-20 lg:py-24">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Articles by Salah Eddine Arbani
            </h2>
            <p className="max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Explore the latest insights and perspectives from Salah Eddine Arbani.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <TwitterIcon className="h-6 w-6 text-muted-foreground" />
            <GitlabIcon className="h-6 w-6 text-muted-foreground" />
            <LinkedinIcon className="h-6 w-6 text-muted-foreground" />
          </div>
        </div>
        <div className="grid gap-6 py-12 md:grid-cols-2 lg:grid-cols-3 lg:gap-8">
          <div className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 transition-transform duration-300 ease-in-out">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">Read article</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Article Thumbnail"
              width={600}
              height={400}
              className="object-cover w-full h-64"
              style={{ aspectRatio: "600/400", objectFit: "cover" }}
            />
            <div className="p-4 bg-background">
              <h3 className="text-xl font-bold">Unlocking the Power of React Hooks</h3>
              <p className="text-sm text-muted-foreground">
                Discover how React Hooks can revolutionize your development workflow.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Link href="#" className="text-primary font-medium hover:underline" prefetch={false}>
                  Read More
                </Link>
                <ArrowRightIcon className="h-4 w-4 text-primary" />
              </div>
            </div>
          </div>
          <div className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 transition-transform duration-300 ease-in-out">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">Read article</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Article Thumbnail"
              width={600}
              height={400}
              className="object-cover w-full h-64"
              style={{ aspectRatio: "600/400", objectFit: "cover" }}
            />
            <div className="p-4 bg-background">
              <h3 className="text-xl font-bold">Mastering Responsive Design with CSS</h3>
              <p className="text-sm text-muted-foreground">
                Learn how to create stunning responsive layouts that adapt to any device.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Link href="#" className="text-primary font-medium hover:underline" prefetch={false}>
                  Read More
                </Link>
                <ArrowRightIcon className="h-4 w-4 text-primary" />
              </div>
            </div>
          </div>
          <div className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 transition-transform duration-300 ease-in-out">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">Read article</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Article Thumbnail"
              width={600}
              height={400}
              className="object-cover w-full h-64"
              style={{ aspectRatio: "600/400", objectFit: "cover" }}
            />
            <div className="p-4 bg-background">
              <h3 className="text-xl font-bold">Optimizing Web Performance with Webpack</h3>
              <p className="text-sm text-muted-foreground">
                Dive into the world of Webpack and learn how to boost your website's speed.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Link href="#" className="text-primary font-medium hover:underline" prefetch={false}>
                  Read More
                </Link>
                <ArrowRightIcon className="h-4 w-4 text-primary" />
              </div>
            </div>
          </div>
          <div className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 transition-transform duration-300 ease-in-out">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">Read article</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Article Thumbnail"
              width={600}
              height={400}
              className="object-cover w-full h-64"
              style={{ aspectRatio: "600/400", objectFit: "cover" }}
            />
            <div className="p-4 bg-background">
              <h3 className="text-xl font-bold">Exploring the Potential of TypeScript</h3>
              <p className="text-sm text-muted-foreground">
                Discover how TypeScript can enhance your JavaScript development experience.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Link href="#" className="text-primary font-medium hover:underline" prefetch={false}>
                  Read More
                </Link>
                <ArrowRightIcon className="h-4 w-4 text-primary" />
              </div>
            </div>
          </div>
          <div className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 transition-transform duration-300 ease-in-out">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">Read article</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Article Thumbnail"
              width={600}
              height={400}
              className="object-cover w-full h-64"
              style={{ aspectRatio: "600/400", objectFit: "cover" }}
            />
            <div className="p-4 bg-background">
              <h3 className="text-xl font-bold">Designing Accessible User Interfaces</h3>
              <p className="text-sm text-muted-foreground">
                Learn how to create inclusive and accessible web experiences for all users.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Link href="#" className="text-primary font-medium hover:underline" prefetch={false}>
                  Read More
                </Link>
                <ArrowRightIcon className="h-4 w-4 text-primary" />
              </div>
            </div>
          </div>
          <div className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 transition-transform duration-300 ease-in-out">
            <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
              <span className="sr-only">Read article</span>
            </Link>
            <img
              src="/placeholder.svg"
              alt="Article Thumbnail"
              width={600}
              height={400}
              className="object-cover w-full h-64"
              style={{ aspectRatio: "600/400", objectFit: "cover" }}
            />
            <div className="p-4 bg-background">
              <h3 className="text-xl font-bold">Scaling Your React Application with Redux</h3>
              <p className="text-sm text-muted-foreground">
                Discover how Redux can help you manage the state of your complex React apps.
              </p>
              <div className="mt-4 flex items-center justify-between">
                <Link href="#" className="text-primary font-medium hover:underline" prefetch={false}>
                  Read More
                </Link>
                <ArrowRightIcon className="h-4 w-4 text-primary" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function GitlabIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
