/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eB86TkfDfSi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function SalahTestimonials() {
  return (
    <section className="py-12 md:py-24 lg:py-32">
      <div className="container grid max-w-5xl gap-8 px-4 md:px-6">
        <div className="space-y-4 text-center">
          <div className="inline-flex items-center rounded-lg bg-muted px-3 py-1 text-sm">
            <StarIcon className="mr-2 h-4 w-4" />
            Testimonials
          </div>
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">What People Are Saying</h2>
          <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Hear from our satisfied clients, colleagues, and mentors about their experience working with us.
          </p>
        </div>
        <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3">
          <Card className="space-y-4 p-6">
            <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
              &ldquo;The team at Acme Inc. has been an invaluable partner in helping us grow our business. Their
              expertise and professionalism are unmatched.&rdquo;
            </blockquote>
            <div className="flex items-center gap-2">
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="Jane Doe" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-semibold">Jane Doe</div>
                <div className="text-sm text-muted-foreground">CEO, Startup Co.</div>
              </div>
            </div>
          </Card>
          <Card className="space-y-4 p-6">
            <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
              &ldquo;I've had the pleasure of working with Acme Inc. on several projects, and I'm always impressed by
              their attention to detail and commitment to excellence.&rdquo;
            </blockquote>
            <div className="flex items-center gap-2">
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="John Smith" />
                <AvatarFallback>JS</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-semibold">John Smith</div>
                <div className="text-sm text-muted-foreground">Senior Developer, Tech Co.</div>
              </div>
            </div>
          </Card>
          <Card className="space-y-4 p-6">
            <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
              &ldquo;Acme Inc. has been an invaluable mentor to me throughout my career. Their guidance and support have
              been instrumental in my professional growth.&rdquo;
            </blockquote>
            <div className="flex items-center gap-2">
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="Sarah Lee" />
                <AvatarFallback>SL</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-semibold">Sarah Lee</div>
                <div className="text-sm text-muted-foreground">Freelance Designer</div>
              </div>
            </div>
          </Card>
          <Card className="space-y-4 p-6">
            <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
              &ldquo;I've had the pleasure of working with Acme Inc. on several projects, and I'm always impressed by
              their attention to detail and commitment to excellence.&rdquo;
            </blockquote>
            <div className="flex items-center gap-2">
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="Michael Johnson" />
                <AvatarFallback>MJ</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-semibold">Michael Johnson</div>
                <div className="text-sm text-muted-foreground">Marketing Manager, Enterprise Co.</div>
              </div>
            </div>
          </Card>
          <Card className="space-y-4 p-6">
            <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
              &ldquo;The team at Acme Inc. has been an invaluable partner in helping us grow our business. Their
              expertise and professionalism are unmatched.&rdquo;
            </blockquote>
            <div className="flex items-center gap-2">
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="Emily Chen" />
                <AvatarFallback>EC</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-semibold">Emily Chen</div>
                <div className="text-sm text-muted-foreground">Founder, Startup Co.</div>
              </div>
            </div>
          </Card>
          <Card className="space-y-4 p-6">
            <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
              &ldquo;Acme Inc. has been an invaluable mentor to me throughout my career. Their guidance and support have
              been instrumental in my professional growth.&rdquo;
            </blockquote>
            <div className="flex items-center gap-2">
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="David Lee" />
                <AvatarFallback>DL</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-semibold">David Lee</div>
                <div className="text-sm text-muted-foreground">Product Manager, Tech Co.</div>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </section>
  )
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
